---
# This file is ONLY for variables that may be overridden during the image BUILD
# phase.
mysql_dockerize_context: docker
mysql_repository_mirror: "{{ mysql_repository_mirror }}"
mysql_version: "{{ mysql_version }}"
