---
- name: ensure docker image build directories exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  with_items:
    - "{{ ansible_env.PWD }}/.ansible_cache"
    - "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild"
  when: mysql_docker_build_image

- name: synchronize role to remote cache for Dockerfile build
  synchronize:
    src: ../
    dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/mysql"
    archive: no
    checksum: yes
    recursive: yes
  when: mysql_docker_build_image

- name: ensure docker image configuration directory exists
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  with_items:
    - "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/mysql/provisioning/group_vars"
  when: mysql_docker_build_image

- name: update configuration used to build docker image from template
  template:
    src: ansible_cache/dockerbuild/mysql/provisioning/group_vars/all.yml
    owner: "{{ ansible_ssh_user }}"
    dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/mysql/provisioning/group_vars/all.yml"
  when: mysql_docker_build_image

- name: ensure mysql docker image has been built
  docker_image:
    name: "{{ mysql_docker_username }}/{{ mysql_docker_imagename }}"
    path: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/mysql"
    state: present
  when: mysql_docker_build_image

- name: ensure mysql data container exists
  docker:
    image: "{{ mysql_docker_username }}/{{ mysql_docker_imagename }}"
    name: "{{ mysql_docker_containername }}_data"
    command: /bin/true
    detach: no
    state: present

- name: ensure mysql service is running
  docker:
    image: "{{ mysql_docker_username }}/{{ mysql_docker_imagename }}"
    name: "{{ mysql_docker_containername }}_server"
    volumes_from: "{{ mysql_docker_containername }}_data"
    ports: "{{ mysql_bind_address }}:{{ mysql_port }}:3306"
    detach: yes
    env: 
      - mysql_root_password={{ mysql_mysql_root_password }}
    state: running
  register: server_startup

- name: block until the service configuration has been completed
  mysql_user:
    login_host: "{{ mysql_bind_address }}"
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ mysql_mysql_root_password }}"
    name: root
    password: "{{ mysql_mysql_root_password }}"
    host: localhost
    state: present
  register: server_connect
  until: server_connect|success
  retries: 30
  delay: 1
