---
- name: ensure mysql dependency packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-mysqldb
    - python-software-properties

- name: ensure mysql packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - mysql-server
    - mysql-client
