---
- include: prep.yml

- include: docker.yml
  when: mysql_dockerized_deployment

- include: install.yml
  when: not mysql_dockerized_deployment

- include: configure.yml
  when: not mysql_dockerized_deployment 
