---
- hosts: all
  sudo: True
  tasks:

    - name: ensure test user account exists
      mysql_user:
        login_host: "{{ mysql_bind_address }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_mysql_root_password }}"
        name: test
        password: test
        host: localhost
        state: present
